-- =============================================================================
-- 01_schema_create_postgres.sql
-- DevDB v10 schema -- PostgreSQL version
-- Converted from 01_schema_create_v10.sql (Databricks Unity Catalog)
-- Changes from Databricks version:
--   main.devdb. prefix removed -- use devdb schema
--   STRING -> TEXT
--   TIMESTAMP -> TIMESTAMPTZ
--   GENERATED BY DEFAULT AS IDENTITY -- standard SQL, supported in Postgres 10+
--   No USING DELTA or Delta Lake-specific clauses
--   checkpoint_lead_days added to sim_takedown_agreements (was missing from original)
--   ALTER TABLE for dim_development removed (populated by migration script)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS devdb;
SET search_path TO devdb;


-- -----------------------------------------------------------------------------
-- 1. dim_projection_groups
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.dim_projection_groups (
    projection_group_id  BIGINT     GENERATED BY DEFAULT AS IDENTITY,
    dev_id               INT        NOT NULL,
    lot_type_id          INT        NOT NULL,
    county_id            INT        NOT NULL,
    school_district_id   INT        NOT NULL,
    needs_rerun          BOOLEAN,
    created_at           TIMESTAMPTZ,
    CONSTRAINT pk_dim_projection_groups PRIMARY KEY (projection_group_id)
);


-- -----------------------------------------------------------------------------
-- 2. ref_lot_types
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.ref_lot_types (
    lot_type_id             INT     NOT NULL,
    lot_type_name           TEXT,
    lot_type_short          TEXT,
    proj_lot_type_group_id  INT,
    lot_type_group_id       INT,
    units_per_building      INT,
    active                  BOOLEAN,
    CONSTRAINT pk_ref_lot_types PRIMARY KEY (lot_type_id)
);


-- -----------------------------------------------------------------------------
-- 3. sim_entitlement_groups
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_entitlement_groups (
    ent_group_id          BIGINT   NOT NULL,
    ent_group_name        TEXT,
    date_ent_actual       DATE,
    date_ent_projected    DATE,
    lot_count_authorized  INT,
    notes                 TEXT,
    created_at            TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT pk_sim_entitlement_groups PRIMARY KEY (ent_group_id)
);


-- -----------------------------------------------------------------------------
-- 4. sim_entitlement_delivery_config
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_entitlement_delivery_config (
    ent_group_id              BIGINT   NOT NULL,
    max_deliveries_per_year   INT,
    delivery_window_start     INT,
    delivery_window_end       INT,
    min_gap_months            INT,
    auto_schedule_enabled     BOOLEAN,
    updated_at                TIMESTAMPTZ,
    updated_by                TEXT,
    CONSTRAINT pk_sim_entitlement_delivery_config PRIMARY KEY (ent_group_id),
    CONSTRAINT fk_sim_entdlvcfg_ent_group FOREIGN KEY (ent_group_id)
        REFERENCES devdb.sim_entitlement_groups (ent_group_id)
);


-- -----------------------------------------------------------------------------
-- 5. sim_ent_group_developments
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_ent_group_developments (
    id            BIGINT  NOT NULL,
    ent_group_id  BIGINT  NOT NULL,
    dev_id        INT     NOT NULL,
    CONSTRAINT pk_sim_ent_group_developments PRIMARY KEY (id),
    CONSTRAINT fk_sim_entgrpdev_ent_group FOREIGN KEY (ent_group_id)
        REFERENCES devdb.sim_entitlement_groups (ent_group_id)
);


-- -----------------------------------------------------------------------------
-- 6. sim_dev_defaults
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_dev_defaults (
    dev_id                INT  NOT NULL,
    default_lot_type_id   INT,
    default_county_id     INT,
    default_school_id     INT,
    CONSTRAINT pk_sim_dev_defaults PRIMARY KEY (dev_id),
    CONSTRAINT fk_sim_devdef_lot_type FOREIGN KEY (default_lot_type_id)
        REFERENCES devdb.ref_lot_types (lot_type_id)
);


-- -----------------------------------------------------------------------------
-- 7. sim_delivery_events
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_delivery_events (
    delivery_event_id          BIGINT   NOT NULL,
    ent_group_id               BIGINT   NOT NULL,
    event_name                 TEXT,
    predecessor_type           TEXT,
    delivery_window_start      INT,
    delivery_window_end        INT,
    date_dev_actual            DATE,
    date_dev_projected         DATE,
    is_auto_created            BOOLEAN,
    is_placeholder             BOOLEAN,
    placeholder_cadence_months INT,
    notes                      TEXT,
    created_at                 TIMESTAMPTZ,
    updated_at                 TIMESTAMPTZ,
    CONSTRAINT pk_sim_delivery_events PRIMARY KEY (delivery_event_id),
    CONSTRAINT fk_sim_delivevt_ent_group FOREIGN KEY (ent_group_id)
        REFERENCES devdb.sim_entitlement_groups (ent_group_id)
);


-- -----------------------------------------------------------------------------
-- 8. sim_delivery_event_predecessors
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_delivery_event_predecessors (
    id                   BIGINT  NOT NULL,
    event_id             BIGINT  NOT NULL,
    predecessor_event_id BIGINT  NOT NULL,
    CONSTRAINT pk_sim_delivery_event_predecessors PRIMARY KEY (id),
    CONSTRAINT fk_sim_delivevtpred_event FOREIGN KEY (event_id)
        REFERENCES devdb.sim_delivery_events (delivery_event_id),
    CONSTRAINT fk_sim_delivevtpred_predecessor FOREIGN KEY (predecessor_event_id)
        REFERENCES devdb.sim_delivery_events (delivery_event_id)
);


-- -----------------------------------------------------------------------------
-- 9. sim_legal_instruments
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_legal_instruments (
    instrument_id    BIGINT  NOT NULL,
    dev_id           INT     NOT NULL,
    instrument_name  TEXT,
    instrument_type  TEXT,
    recorded_date    DATE,
    notes            TEXT,
    created_at       TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_sim_legal_instruments PRIMARY KEY (instrument_id)
);


-- -----------------------------------------------------------------------------
-- 10. sim_dev_phases
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_dev_phases (
    phase_id                BIGINT  NOT NULL,
    instrument_id           BIGINT,
    dev_id                  INT     NOT NULL,
    source_dvp_id           INT,
    phase_name              TEXT,
    sequence_number         INT,
    lot_count_projected     INT,
    date_dev_demand_derived DATE,
    date_dev_projected      DATE,
    developer_override      INT,
    inex_override           INT,
    notes                   TEXT,
    created_at              TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ,
    CONSTRAINT pk_sim_dev_phases PRIMARY KEY (phase_id),
    CONSTRAINT fk_sim_devphase_instrument FOREIGN KEY (instrument_id)
        REFERENCES devdb.sim_legal_instruments (instrument_id)
);


-- -----------------------------------------------------------------------------
-- 11. sim_delivery_event_phases
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_delivery_event_phases (
    id                BIGINT  NOT NULL,
    delivery_event_id BIGINT  NOT NULL,
    phase_id          BIGINT  NOT NULL,
    CONSTRAINT pk_sim_delivery_event_phases PRIMARY KEY (id),
    CONSTRAINT fk_sim_delivevtphase_event FOREIGN KEY (delivery_event_id)
        REFERENCES devdb.sim_delivery_events (delivery_event_id),
    CONSTRAINT fk_sim_delivevtphase_phase FOREIGN KEY (phase_id)
        REFERENCES devdb.sim_dev_phases (phase_id)
);


-- -----------------------------------------------------------------------------
-- 12. sim_phase_product_splits
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_phase_product_splits (
    split_id     BIGINT  NOT NULL,
    phase_id     BIGINT  NOT NULL,
    lot_type_id  INT     NOT NULL,
    lot_count    INT,
    CONSTRAINT pk_sim_phase_product_splits PRIMARY KEY (split_id),
    CONSTRAINT fk_sim_phaseprod_phase FOREIGN KEY (phase_id)
        REFERENCES devdb.sim_dev_phases (phase_id),
    CONSTRAINT fk_sim_phaseprod_lot_type FOREIGN KEY (lot_type_id)
        REFERENCES devdb.ref_lot_types (lot_type_id)
);


-- -----------------------------------------------------------------------------
-- 13. sim_phase_builder_splits
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_phase_builder_splits (
    split_id    BIGINT         NOT NULL,
    phase_id    BIGINT         NOT NULL,
    builder_id  INT,
    share       DECIMAL(5,4),
    CONSTRAINT pk_sim_phase_builder_splits PRIMARY KEY (split_id),
    CONSTRAINT fk_sim_phasebldr_phase FOREIGN KEY (phase_id)
        REFERENCES devdb.sim_dev_phases (phase_id)
);


-- -----------------------------------------------------------------------------
-- 14. sim_building_groups
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_building_groups (
    building_group_id  BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    dev_id             INT     NOT NULL,
    building_name      TEXT,
    building_type      TEXT,
    unit_count         INT,
    notes              TEXT,
    created_at         TIMESTAMPTZ,
    CONSTRAINT pk_sim_building_groups PRIMARY KEY (building_group_id)
);


-- -----------------------------------------------------------------------------
-- 15. sim_lots
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_lots (
    lot_id               BIGINT   NOT NULL,
    projection_group_id  BIGINT   NOT NULL,
    phase_id             BIGINT   NOT NULL,
    builder_id           INT,
    lot_source           TEXT     NOT NULL,
    lot_number           TEXT,
    sim_run_id           BIGINT,
    lot_type_id          INT      NOT NULL,
    building_group_id    BIGINT,
    date_ent             DATE,
    date_dev             DATE,
    date_td              DATE,
    date_td_hold         DATE,
    date_str             DATE,
    date_str_source      TEXT,
    date_frm             DATE,
    date_cmp             DATE,
    date_cmp_source      TEXT,
    date_cls             DATE,
    date_cls_source      TEXT,
    created_at           TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT pk_sim_lots PRIMARY KEY (lot_id),
    CONSTRAINT fk_sim_lots_projection_group FOREIGN KEY (projection_group_id)
        REFERENCES devdb.dim_projection_groups (projection_group_id),
    CONSTRAINT fk_sim_lots_phase FOREIGN KEY (phase_id)
        REFERENCES devdb.sim_dev_phases (phase_id),
    CONSTRAINT fk_sim_lots_lot_type FOREIGN KEY (lot_type_id)
        REFERENCES devdb.ref_lot_types (lot_type_id)
);

CREATE INDEX IF NOT EXISTS idx_sim_lots_pg_source
    ON devdb.sim_lots (projection_group_id, lot_source);
CREATE INDEX IF NOT EXISTS idx_sim_lots_phase
    ON devdb.sim_lots (phase_id);


-- -----------------------------------------------------------------------------
-- 16. sim_projection_params
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_projection_params (
    projection_group_id   BIGINT   NOT NULL,
    annual_starts_target  INT,
    max_starts_per_month  INT,
    seasonal_weight_set   TEXT,
    custom_weights_json   TEXT,
    str_to_cmp_curve_id   INT,
    cmp_to_cls_curve_id   INT,
    updated_at            TIMESTAMPTZ,
    updated_by            TEXT,
    CONSTRAINT pk_sim_projection_params PRIMARY KEY (projection_group_id),
    CONSTRAINT fk_sim_projparams_proj_group FOREIGN KEY (projection_group_id)
        REFERENCES devdb.dim_projection_groups (projection_group_id)
);


-- -----------------------------------------------------------------------------
-- 17. sim_runs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_runs (
    sim_run_id          BIGINT   NOT NULL,
    projection_group_id BIGINT   NOT NULL,
    run_timestamp       TIMESTAMPTZ,
    run_by              TEXT,
    params_json         TEXT,
    status              TEXT,
    notes               TEXT,
    CONSTRAINT pk_sim_runs PRIMARY KEY (sim_run_id),
    CONSTRAINT fk_sim_runs_proj_group FOREIGN KEY (projection_group_id)
        REFERENCES devdb.dim_projection_groups (projection_group_id)
);


-- -----------------------------------------------------------------------------
-- 18. sim_snapshots
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_snapshots (
    snapshot_id         BIGINT   NOT NULL,
    projection_group_id BIGINT   NOT NULL,
    snapshot_name       TEXT,
    snapshot_type       TEXT,
    snapshot_date       DATE,
    notes               TEXT,
    created_by          TEXT,
    created_at          TIMESTAMPTZ,
    params_json         TEXT,
    ledger_json         TEXT,
    CONSTRAINT pk_sim_snapshots PRIMARY KEY (snapshot_id),
    CONSTRAINT fk_sim_snapshots_proj_group FOREIGN KEY (projection_group_id)
        REFERENCES devdb.dim_projection_groups (projection_group_id)
);


-- -----------------------------------------------------------------------------
-- 19. sim_snapshot_lots
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_snapshot_lots (
    snapshot_lot_id      BIGINT  NOT NULL,
    snapshot_id          BIGINT  NOT NULL,
    lot_id               BIGINT,
    projection_group_id  BIGINT,
    phase_id             BIGINT,
    builder_id           INT,
    lot_source           TEXT,
    lot_number           TEXT,
    sim_run_id           BIGINT,
    lot_type_id          INT,
    building_group_id    BIGINT,
    date_ent             DATE,
    date_dev             DATE,
    date_td              DATE,
    date_td_hold         DATE,
    date_str             DATE,
    date_str_source      TEXT,
    date_frm             DATE,
    date_cmp             DATE,
    date_cmp_source      TEXT,
    date_cls             DATE,
    date_cls_source      TEXT,
    created_at           TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT pk_sim_snapshot_lots PRIMARY KEY (snapshot_lot_id),
    CONSTRAINT fk_sim_snaplots_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES devdb.sim_snapshots (snapshot_id)
);


-- -----------------------------------------------------------------------------
-- 20. sim_projection_actuals
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_projection_actuals (
    actual_id           BIGINT  NOT NULL,
    projection_group_id BIGINT  NOT NULL,
    builder_id          INT,
    actual_year         INT,
    actual_month        INT,
    actual_starts       INT,
    actual_closings     INT,
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_sim_projection_actuals PRIMARY KEY (actual_id),
    CONSTRAINT fk_sim_projactuals_proj_group FOREIGN KEY (projection_group_id)
        REFERENCES devdb.dim_projection_groups (projection_group_id)
);


-- -----------------------------------------------------------------------------
-- 21. sim_lot_date_violations
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_lot_date_violations (
    violation_id      BIGINT  NOT NULL,
    sim_run_id        BIGINT  NOT NULL,
    lot_id            BIGINT  NOT NULL,
    violation_type    TEXT,
    date_field_early  TEXT,
    date_value_early  DATE,
    date_field_late   TEXT,
    date_value_late   DATE,
    resolution        TEXT,
    created_at        TIMESTAMPTZ,
    CONSTRAINT pk_sim_lot_date_violations PRIMARY KEY (violation_id)
);


-- -----------------------------------------------------------------------------
-- 22. sync_orphaned_lots
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sync_orphaned_lots (
    orphan_id       BIGINT      NOT NULL,
    developmentcode TEXT,
    housenumber     INT,
    derived_key     TEXT,
    status          TEXT,
    first_seen_at   TIMESTAMPTZ,
    sync_count      INT,
    flagged         BOOLEAN,
    resolved_at     TIMESTAMPTZ,
    CONSTRAINT pk_sync_orphaned_lots PRIMARY KEY (orphan_id)
);


-- -----------------------------------------------------------------------------
-- 23. sim_takedown_agreements
-- checkpoint_lead_days: days before checkpoint to schedule hold (default 16)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_takedown_agreements (
    tda_id               BIGINT  NOT NULL,
    tda_name             TEXT,
    agreement_date       DATE,
    anchor_type          TEXT,
    anchor_date          DATE,
    status               TEXT,
    checkpoint_lead_days INT,
    notes                TEXT,
    created_at           TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT pk_sim_takedown_agreements PRIMARY KEY (tda_id)
);


-- -----------------------------------------------------------------------------
-- 24. sim_takedown_agreement_lots
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_takedown_agreement_lots (
    id      BIGINT  NOT NULL,
    tda_id  BIGINT  NOT NULL,
    lot_id  BIGINT  NOT NULL,
    CONSTRAINT pk_sim_takedown_agreement_lots PRIMARY KEY (id),
    CONSTRAINT fk_sim_tdagrplots_tda FOREIGN KEY (tda_id)
        REFERENCES devdb.sim_takedown_agreements (tda_id)
);


-- -----------------------------------------------------------------------------
-- 25. sim_takedown_checkpoints
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_takedown_checkpoints (
    checkpoint_id              BIGINT  NOT NULL,
    tda_id                     BIGINT  NOT NULL,
    checkpoint_number          INT,
    lots_required_cumulative   INT,
    days_offset_from_anchor    INT,
    anchor_date_ref            DATE,
    checkpoint_date            DATE,
    notes                      TEXT,
    CONSTRAINT pk_sim_takedown_checkpoints PRIMARY KEY (checkpoint_id),
    CONSTRAINT fk_sim_tdachkpt_tda FOREIGN KEY (tda_id)
        REFERENCES devdb.sim_takedown_agreements (tda_id)
);


-- -----------------------------------------------------------------------------
-- 26. sim_takedown_lot_assignments
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.sim_takedown_lot_assignments (
    assignment_id  BIGINT  NOT NULL,
    checkpoint_id  BIGINT  NOT NULL,
    lot_id         BIGINT  NOT NULL,
    assigned_at    TIMESTAMPTZ,
    CONSTRAINT pk_sim_takedown_lot_assignments PRIMARY KEY (assignment_id),
    CONSTRAINT fk_sim_tdalotasgn_checkpoint FOREIGN KEY (checkpoint_id)
        REFERENCES devdb.sim_takedown_checkpoints (checkpoint_id)
);


-- -----------------------------------------------------------------------------
-- 27. schedhousedetail  (MARKsystems activity log, 266k+ rows)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devdb.schedhousedetail (
    developmentcode   TEXT,
    housenumber       INT,
    activitycode      TEXT,
    actualfinishdate  DATE,
    rvearlyfinshdate  DATE,
    earlyfinishdate   DATE,
    inactive          TEXT
);

CREATE INDEX IF NOT EXISTS idx_sched_devcode_act
    ON devdb.schedhousedetail (developmentcode, activitycode);
