-- Migration 056: Phase building config + clean sim_building_groups
--
-- 1. Create sim_phase_building_config: stores building size composition per phase
--    (e.g. 6 duplexes + 2 quad-plexes). Engine uses this to generate grouped sim lots
--    and to derive projected_count (SUM(building_count * units_per_building)).
--
-- 2. Drop building_type from sim_building_groups: was manually maintained, now derived
--    from COUNT(lots in group) at query time.
--
-- 3. Drop unit_count from sim_building_groups: redundant with COUNT(lots in group),
--    always in sync (confirmed by data audit 2026-04-15).

CREATE TABLE IF NOT EXISTS devdb.sim_phase_building_config (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id           INTEGER NOT NULL REFERENCES devdb.sim_dev_phases(phase_id) ON DELETE CASCADE,
    building_count     INTEGER NOT NULL CHECK (building_count > 0),
    units_per_building INTEGER NOT NULL CHECK (units_per_building > 0),
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spbc_phase_id
    ON devdb.sim_phase_building_config(phase_id);

ALTER TABLE devdb.sim_building_groups
    DROP COLUMN IF EXISTS building_type,
    DROP COLUMN IF EXISTS unit_count;
